import { Collection, Snippet } from '../types';

export const dummySnippets: Snippet[] = [
  {
    _id: 's1',
    title: 'React Custom Hook: useFetch',
    description: 'A custom React hook for data fetching with loading and error states.',
    code: `import { useState, useEffect } from 'react';\n\nexport const useFetch = (url) => {\n  const [data, setData] = useState(null);\n  const [loading, setLoading] = useState(true);\n  \n  useEffect(() => {\n    fetch(url)\n      .then(res => res.json())\n      .then(data => {\n        setData(data);\n        setLoading(false);\n      });\n  }, [url]);\n\n  return { data, loading };\n};`,
    language: 'javascript',
    tags: ['react', 'hooks', 'fetch'],
    category: 'Frontend',
    isPublic: true,
    author: 'u1',
    favoritesCount: 12,
    isFavorited: true,
    viewsCount: 156,
    forksCount: 3,
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    _id: 's2',
    title: 'Express JWT Middleware',
    description: 'Middleware to verify JSON Web Tokens in Express.',
    code: `const jwt = require('jsonwebtoken');\n\nconst auth = (req, res, next) => {\n  const token = req.header('x-auth-token');\n  if (!token) return res.status(401).send('Access denied.');\n\n  try {\n    const decoded = jwt.verify(token, process.env.JWT_SECRET);\n    req.user = decoded;\n    next();\n  } catch (ex) {\n    res.status(400).send('Invalid token.');\n  }\n};`,
    language: 'javascript',
    tags: ['express', 'jwt', 'auth'],
    category: 'Backend',
    isPublic: true,
    author: 'u1',
    favoritesCount: 8,
    isFavorited: false,
    viewsCount: 89,
    forksCount: 1,
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    _id: 's3',
    title: 'Tailwind Card Component',
    description: 'A beautiful responsive card component using Tailwind CSS.',
    code: `<div className="max-w-sm rounded overflow-hidden shadow-lg bg-white">\n  <div className="px-6 py-4">\n    <div className="font-bold text-xl mb-2">The Coldest Sunset</div>\n    <p className="text-gray-700 text-base">\n      Lorem ipsum dolor sit amet, consectetur adipisicing elit.\n    </p>\n  </div>\n  <div className="px-6 pt-4 pb-2">\n    <span className="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">#photography</span>\n  </div>\n</div>`,
    language: 'html',
    tags: ['tailwind', 'css', 'ui'],
    category: 'Frontend',
    isPublic: true,
    author: 'u1',
    favoritesCount: 24,
    isFavorited: true,
    viewsCount: 302,
    forksCount: 5,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  }
];

export const dummyCollections: Collection[] = [
  {
    _id: 'c1',
    name: 'React Fundamentals',
    description: 'Essential React snippets including hooks, contexts, and common components.',
    snippets: [dummySnippets[0]],
    user: 'u1',
    isPublic: true,
    createdAt: new Date(Date.now() - 86400000 * 10).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    _id: 'c2',
    name: 'Backend Utils',
    description: 'Node.js and Express utility functions, middleware, and helpers.',
    snippets: [dummySnippets[1]],
    user: 'u1',
    isPublic: false,
    createdAt: new Date(Date.now() - 86400000 * 20).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    _id: 'c3',
    name: 'UI Components',
    description: 'Reusable UI components built with Tailwind CSS.',
    snippets: [dummySnippets[2]],
    user: 'u1',
    isPublic: true,
    createdAt: new Date(Date.now() - 86400000 * 30).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    _id: 'c4',
    name: 'Machine Learning',
    description: 'Python snippets for data processing and model training.',
    snippets: [],
    user: 'u1',
    isPublic: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
];
